/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import lib.koneksi;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.ButtonGroup;

/**
 *
 * @author Ganda
 */
public class F_Formkontak extends javax.swing.JFrame {

    /**
     * Creates new form F_Formkontak
     */
    private koneksi kon;
    private String nama,nomorhp,batastxt;
    private int keterangan;
    private String kueri;
    private String inputnomorhp;
    
    public F_Formkontak() {
        initComponents();
        groupButton();
        setResizable(false);
        kon = new koneksi();
        if(F_Kontak.modeformkontak == 1){
            try{
                Statement stasql = (Statement)kon.Connect().createStatement();
                kueri=("select nama,hp,tipe from kontak where id = '"+F_Kontak.n_id+"';");
                ResultSet rs = stasql.executeQuery(kueri);               
                while(rs.next()){
                   String datanama = rs.getString("nama");
                   String datanomorhp = rs.getString("hp");
                   String datatipe = rs.getString("tipe");
                   //JOptionPane.showMessageDialog(null,"Sip");
                   txt_nama.setText(datanama);
                   txt_nomorhp.setText(datanomorhp);
                   if(datatipe.equals("0"))radio_guru.setSelected(true);
                   else if(datatipe.equals("1"))radio_siswa.setSelected(true);
                   else radio_ortusiswa.setSelected(true);                   
                }
                rs.close();
                stasql.close();
            } catch(Exception t){
                JOptionPane.showMessageDialog(null,"Terdapat Kesalahan Pada Program");
            }
        }
    }
    
    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(radio_siswa);
        bg1.add(radio_ortusiswa);
        bg1.add(radio_guru);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_nama = new javax.swing.JTextField();
        txt_nomorhp = new javax.swing.JTextField();
        btn_konfirmasi = new javax.swing.JButton();
        radio_siswa = new javax.swing.JRadioButton();
        radio_guru = new javax.swing.JRadioButton();
        radio_ortusiswa = new javax.swing.JRadioButton();
        lbl_judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nomorhp = new javax.swing.JLabel();
        lbl_keterangan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btn_kembali.setBackground(new java.awt.Color(0, 204, 204));
        btn_kembali.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("BACK");
        btn_kembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_kembaliMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseReleased(evt);
            }
        });
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD");

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        txt_nama.setBackground(new java.awt.Color(0, 51, 51));
        txt_nama.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(255, 255, 255));
        txt_nama.setBorder(null);
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });

        txt_nomorhp.setBackground(new java.awt.Color(0, 51, 51));
        txt_nomorhp.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_nomorhp.setForeground(new java.awt.Color(255, 255, 255));
        txt_nomorhp.setBorder(null);
        txt_nomorhp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomorhpKeyTyped(evt);
            }
        });

        btn_konfirmasi.setBackground(new java.awt.Color(0, 204, 204));
        btn_konfirmasi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_konfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btn_konfirmasi.setText("CONFIRM");
        btn_konfirmasi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_konfirmasi.setContentAreaFilled(false);
        btn_konfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_konfirmasiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_konfirmasiMouseReleased(evt);
            }
        });
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });

        radio_siswa.setBackground(new java.awt.Color(0, 51, 51));
        radio_siswa.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        radio_siswa.setForeground(new java.awt.Color(255, 255, 255));
        radio_siswa.setText("Siswa");

        radio_guru.setBackground(new java.awt.Color(0, 51, 51));
        radio_guru.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        radio_guru.setForeground(new java.awt.Color(255, 255, 255));
        radio_guru.setText("Guru");

        radio_ortusiswa.setBackground(new java.awt.Color(0, 51, 51));
        radio_ortusiswa.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        radio_ortusiswa.setForeground(new java.awt.Color(255, 255, 255));
        radio_ortusiswa.setText("Orang Tua Siswa");

        lbl_judul.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_judul.setForeground(new java.awt.Color(255, 255, 255));
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("Form Contact");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Maximal 50 characters*");

        lbl_name.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Name");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*Maximal 15 Number*");

        lbl_nomorhp.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbl_nomorhp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nomorhp.setText("Phone No.");

        lbl_keterangan.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbl_keterangan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_keterangan.setText("Status            :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_keterangan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_nomorhp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radio_siswa)
                        .addGap(108, 108, 108)
                        .addComponent(radio_guru))
                    .addComponent(radio_ortusiswa)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_nomorhp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_nama)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lbl_judul)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomorhp)
                    .addComponent(txt_nomorhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_keterangan)
                    .addComponent(radio_siswa)
                    .addComponent(radio_guru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_ortusiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 34)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTACT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        this.setVisible(false);
        new F_Kontak().setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        if(F_Kontak.modeformkontak == 1){
            nama = txt_nama.getText();
            nomorhp = txt_nomorhp.getText();
            if(radio_siswa.isSelected())keterangan = 1;
            if(radio_ortusiswa.isSelected())keterangan = 2;
            if(radio_guru.isSelected())keterangan = 0;
            
            if(nama.length() != 0 && nomorhp.length() != 0 && keterangan != 9){
                try{
                    Statement stasql = (Statement)kon.Connect().createStatement(); 
                    kueri=("update kontak set nama = '"+nama+"', hp = '"+nomorhp+"', tipe = '"+keterangan+"' where id = '"+F_Kontak.n_id+"';");
                    stasql.executeUpdate(kueri);
                    stasql.close();
                    JOptionPane.showMessageDialog(null,"Record Telah Diubah");
                    this.setVisible(false);
                    new F_Kontak().setVisible(true);
                } catch(Exception t){
                    JOptionPane.showMessageDialog(null,"Record Gagal Ditambah\nTerdapat Kesalahan Pada Program");
                }
            }
        }
        else {
            keterangan = 9;
            nama = txt_nama.getText();
            nomorhp = txt_nomorhp.getText();
            if(radio_siswa.isSelected())keterangan = 1;
            if(radio_ortusiswa.isSelected())keterangan = 2;
            if(radio_guru.isSelected())keterangan = 0;

            if(nama.length() != 0 && nomorhp.length() != 0 && keterangan != 9){
                try{
                    Statement stasql = (Statement)kon.Connect().createStatement();
                    kueri=("insert into kontak (nama,hp,tipe) values ('"+nama+"','"+nomorhp+"','"+keterangan+"');");
                    stasql.executeUpdate(kueri);
                    stasql.close();
                    JOptionPane.showMessageDialog(null,"Record Telah Ditambah");
                    this.setVisible(false);
                    new F_Kontak().setVisible(true);
                } catch(Exception t){
                    JOptionPane.showMessageDialog(null,"Record Gagal Ditambah\nTerdapat Kesalahan Pada Program");
                }
            }
        }
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
        if(txt_nama.getText().length()<50){
            txt_nama.setEditable(true);
        }
        else {
            batastxt = txt_nama.getText().substring(0, 49);
            txt_nama.setText(batastxt);
        }
    }//GEN-LAST:event_txt_namaKeyTyped

    private void txt_nomorhpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomorhpKeyTyped
        char c = evt.getKeyChar();
        if(!((Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)))){
            evt.consume();
        }
        inputnomorhp = txt_nomorhp.getText();
        if(inputnomorhp.length()<15){
            txt_nomorhp.setEditable(true);
        }
        else {                    
            batastxt = inputnomorhp.substring(0, 14);
            txt_nomorhp.setText(batastxt);
        }
    }//GEN-LAST:event_txt_nomorhpKeyTyped

    private void btn_kembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMousePressed
       btn_kembali.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_kembaliMousePressed

    private void btn_konfirmasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_konfirmasiMousePressed
        btn_konfirmasi.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_konfirmasiMousePressed

    private void btn_kembaliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseReleased
        btn_kembali.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_kembaliMouseReleased

    private void btn_konfirmasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_konfirmasiMouseReleased
        btn_konfirmasi.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_konfirmasiMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Formkontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Formkontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Formkontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Formkontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Formkontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_keterangan;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nomorhp;
    private javax.swing.JRadioButton radio_guru;
    private javax.swing.JRadioButton radio_ortusiswa;
    private javax.swing.JRadioButton radio_siswa;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nomorhp;
    // End of variables declaration//GEN-END:variables
}
