/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.harshadura.gsm.smsdura.GsmModem;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import lib.koneksi;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ganda
 */
public class F_Kontak extends javax.swing.JFrame {

    /**
     * Creates new form F_Kontak
     */
    private koneksi kon;
    private DefaultTableModel tabel;
    private String kueri;
    private int modekliktabel;
    public static int modeformkontak;
    public static String n_id;
    
    public F_Kontak() {
        initComponents();
        kon = new koneksi();
        tabel = new DefaultTableModel();
        tbl_kontak.setModel(tabel);
        tabel.addColumn("Id");
        tabel.addColumn("Tipe");
        tabel.addColumn("Nama Siswa");
        tabel.addColumn("Nomor Telepon");
        muattabel();
        modeformkontak = 0;
        String n_id = "";
    }
    
    public void muattabel(){
        try{
            Statement stasql = (Statement)kon.Connect().createStatement();
            ResultSet runkueri = stasql.executeQuery("select * from kontak;");
            while (runkueri.next()) {
                tabel.addRow(new Object[]{runkueri.getString(1), runkueri.getString(2),runkueri.getString(3),runkueri.getString(4)});
            }
            stasql.close();
         } catch(Exception t){
            JOptionPane.showMessageDialog(null,"Terdapat Kesalahan");
         }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kontak = new javax.swing.JTable();
        lbl_judul = new javax.swing.JLabel();
        btn_tambahrecord = new javax.swing.JButton();
        btn_editrecord = new javax.swing.JButton();
        btn_hapusrecord = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbl_kontak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_kontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kontakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kontak);

        lbl_judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("KONTAK");

        btn_tambahrecord.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_tambahrecord.setText("Tambah Record");
        btn_tambahrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahrecordActionPerformed(evt);
            }
        });

        btn_editrecord.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_editrecord.setText("Edit Record");
        btn_editrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editrecordActionPerformed(evt);
            }
        });

        btn_hapusrecord.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_hapusrecord.setText("Hapus Record");
        btn_hapusrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusrecordActionPerformed(evt);
            }
        });

        btn_kembali.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_kembali.setText("Kembali");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_editrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tambahrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hapusrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addComponent(lbl_judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_judul)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambahrecord)
                        .addGap(42, 42, 42)
                        .addComponent(btn_editrecord)
                        .addGap(50, 50, 50)
                        .addComponent(btn_hapusrecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kembali))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahrecordActionPerformed
        modeformkontak = 0;
        this.setVisible(false);
        new F_Formkontak().setVisible(true);
    }//GEN-LAST:event_btn_tambahrecordActionPerformed

    private void btn_editrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editrecordActionPerformed
        if(modeformkontak == 1){
            int row = tbl_kontak.getSelectedRow();
            n_id = (String) tbl_kontak.getValueAt(row, 0);
            this.setVisible(false);
            new F_Formkontak().setVisible(true);
        }
    }//GEN-LAST:event_btn_editrecordActionPerformed

    private void tbl_kontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kontakMouseClicked
        modeformkontak = 1;
    }//GEN-LAST:event_tbl_kontakMouseClicked

    private void btn_hapusrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusrecordActionPerformed
        if(modeformkontak == 1){
            int row = tbl_kontak.getSelectedRow();
            n_id = (String) tbl_kontak.getValueAt(row, 0);
            try{
                Statement stasql = (Statement)kon.Connect().createStatement(); 
                kueri=("delete from kontak where id = '"+n_id+"';");
                stasql.executeUpdate(kueri);
                stasql.close();
                JOptionPane.showMessageDialog(null,"Record Telah Dihapus");
                this.setVisible(false);
                new F_Kontak().setVisible(true);
            } catch(Exception t){
                JOptionPane.showMessageDialog(null,"Record Gagal Dihapus\nTerdapat Kesalahan Pada Program");
            }
        }
    }//GEN-LAST:event_btn_hapusrecordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Kontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editrecord;
    private javax.swing.JButton btn_hapusrecord;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambahrecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JTable tbl_kontak;
    // End of variables declaration//GEN-END:variables
}
