/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import lib.koneksi;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ganda
 */
public class F_Kontak extends javax.swing.JFrame {

    /**
     * Creates new form F_Kontak
     */
    private koneksi kon;
    private DefaultTableModel tabel;
    private String kueri;
    private int modekliktabel;
    public static int modeformkontak;
    public static String n_id;
    
    public F_Kontak() {
        initComponents();
        setResizable(false);
        kon = new koneksi();
        tabel = new DefaultTableModel();
        tbl_kontak.setModel(tabel);
        tabel.addColumn("No");
        tabel.addColumn("ID");
        tabel.addColumn("Nama Siswa");
        tabel.addColumn("Nomor Telepon");
        tabel.addColumn("Tipe");
        muattabel();
        modeformkontak = 0;
        String n_id = "";
    }
    
    public void muattabel(){
        try{
            Statement stasql = (Statement)kon.Connect().createStatement();
            ResultSet runkueri = stasql.executeQuery("select * from kontak;");
            int i = 1;
            String tipe = null;
            while (runkueri.next()) {
                switch(runkueri.getString(4)){
                    case "0":
                        tipe = "guru";
                        break;
                    case "1":
                        tipe = "siswa";
                        break;
                    case "2":
                        tipe = "orang tua siswa";
                        break;
                }
                tabel.addRow(new Object[]{i,runkueri.getString(1), runkueri.getString(2),runkueri.getString(3),tipe});
                i++;
            }
            stasql.close();
         } catch(Exception t){
            JOptionPane.showMessageDialog(null,"Terdapat Kesalahan");
         }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_kembali = new javax.swing.JButton();
        lbl_judul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_editrecord = new javax.swing.JButton();
        btn_hapusrecord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kontak = new javax.swing.JTable();
        btn_tambahrecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btn_kembali.setBackground(new java.awt.Color(0, 204, 204));
        btn_kembali.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("BACK");
        btn_kembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_kembali.setContentAreaFilled(false);
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_kembaliMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseReleased(evt);
            }
        });
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        lbl_judul.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        lbl_judul.setForeground(new java.awt.Color(255, 255, 255));
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("KONTAK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        btn_editrecord.setBackground(new java.awt.Color(0, 204, 204));
        btn_editrecord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_editrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_editrecord.setText("EDIT");
        btn_editrecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_editrecord.setContentAreaFilled(false);
        btn_editrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editrecordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_editrecordMouseReleased(evt);
            }
        });
        btn_editrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editrecordActionPerformed(evt);
            }
        });

        btn_hapusrecord.setBackground(new java.awt.Color(0, 204, 204));
        btn_hapusrecord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_hapusrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapusrecord.setText("DELETE");
        btn_hapusrecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_hapusrecord.setContentAreaFilled(false);
        btn_hapusrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_hapusrecordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_hapusrecordMouseReleased(evt);
            }
        });
        btn_hapusrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusrecordActionPerformed(evt);
            }
        });

        tbl_kontak.setBackground(new java.awt.Color(0, 204, 204));
        tbl_kontak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_kontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kontakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kontak);

        btn_tambahrecord.setBackground(new java.awt.Color(0, 204, 204));
        btn_tambahrecord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_tambahrecord.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahrecord.setText("ADD");
        btn_tambahrecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_tambahrecord.setContentAreaFilled(false);
        btn_tambahrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tambahrecordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_tambahrecordMouseReleased(evt);
            }
        });
        btn_tambahrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahrecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_hapusrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambahrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tambahrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapusrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahrecordActionPerformed
        modeformkontak = 0;
        this.setVisible(false);
        new F_Formkontak().setVisible(true);
    }//GEN-LAST:event_btn_tambahrecordActionPerformed

    private void btn_editrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editrecordActionPerformed
        if(modeformkontak == 1){
            int row = tbl_kontak.getSelectedRow();
            n_id = (String) tbl_kontak.getValueAt(row, 1);
            this.setVisible(false);
            new F_Formkontak().setVisible(true);
        }
    }//GEN-LAST:event_btn_editrecordActionPerformed

    private void tbl_kontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kontakMouseClicked
        modeformkontak = 1;
    }//GEN-LAST:event_tbl_kontakMouseClicked

    private void btn_hapusrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusrecordActionPerformed
        if(modeformkontak == 1){
            int row = tbl_kontak.getSelectedRow();
            n_id = (String) tbl_kontak.getValueAt(row, 1);
            try{
                Statement stasql = (Statement)kon.Connect().createStatement(); 
                kueri=("delete from kontak where id = '"+n_id+"';");
                stasql.executeUpdate(kueri);
                stasql.close();
                JOptionPane.showMessageDialog(null,"Record Telah Dihapus");
                this.setVisible(false);
                new F_Kontak().setVisible(true);
            } catch(Exception t){
                JOptionPane.showMessageDialog(null,"Record Gagal Dihapus\nTerdapat Kesalahan Pada Program");
            }
        }
    }//GEN-LAST:event_btn_hapusrecordActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_kembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMousePressed
        btn_kembali.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_kembaliMousePressed

    private void btn_tambahrecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahrecordMousePressed
        btn_tambahrecord.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_tambahrecordMousePressed

    private void btn_editrecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editrecordMousePressed
        btn_editrecord.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_editrecordMousePressed

    private void btn_hapusrecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusrecordMousePressed
        btn_hapusrecord.setBackground(new java.awt.Color(0, 51, 102));
    }//GEN-LAST:event_btn_hapusrecordMousePressed

    private void btn_kembaliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseReleased
        btn_kembali.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_kembaliMouseReleased

    private void btn_tambahrecordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahrecordMouseReleased
        btn_tambahrecord.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_tambahrecordMouseReleased

    private void btn_editrecordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editrecordMouseReleased
        btn_editrecord.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_editrecordMouseReleased

    private void btn_hapusrecordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusrecordMouseReleased
        btn_hapusrecord.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_btn_hapusrecordMouseReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Kontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editrecord;
    private javax.swing.JButton btn_hapusrecord;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambahrecord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JTable tbl_kontak;
    // End of variables declaration//GEN-END:variables
}
