/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Ganda
 */
import com.harshadura.gsm.smsdura.GsmModem;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import lib.koneksi;

import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;

public class F_Register extends javax.swing.JFrame {
    
    /**
     * Creates new form F_Register
     */
    private koneksi kon;
    private String username,password,confpass, batastxt;
    private String kueri;
    private String userpengguna,passpengguna;
    
    public F_Register() {
        initComponents();
        kon = new koneksi();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_judul = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        lbl_txt_username = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_txt_password = new javax.swing.JLabel();
        lbl_confpass = new javax.swing.JLabel();
        txt_confpass = new javax.swing.JPasswordField();
        lbl_txt_confpass = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        lbl_judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("REGISTER");

        lbl_username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_username.setText("Username                     :");

        txt_username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });

        lbl_password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_password.setText("Password                     :");

        lbl_txt_username.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_txt_username.setText("*Maksimal 20 Karakter*");

        txt_password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });

        lbl_txt_password.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_txt_password.setText("*Maksimal 16 Karakter*");

        lbl_confpass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_confpass.setText("Confirmation Password :");

        txt_confpass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_confpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_confpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_confpassKeyTyped(evt);
            }
        });

        lbl_txt_confpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_txt_confpass.setText("*Maksimal 16 Karakter*");

        btn_exit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_register.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_confpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txt_username, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_txt_confpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_password)
                            .addComponent(txt_confpass))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbl_judul)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(txt_username))
                .addGap(5, 5, 5)
                .addComponent(lbl_txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbl_txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confpass)
                    .addComponent(txt_confpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_txt_confpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        if(txt_username.getText().length()<20){
            txt_username.setEditable(true);
        }
        else {
            batastxt = txt_username.getText().substring(0, 19);
            txt_username.setText(batastxt);
        }
    }//GEN-LAST:event_txt_usernameKeyTyped

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
        if(txt_password.getText().length()<16){
            txt_password.setEditable(true);
        }
        else {
            batastxt = txt_password.getText().substring(0, 15);
            txt_password.setText(batastxt);
        }
    }//GEN-LAST:event_txt_passwordKeyTyped

    private void txt_confpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confpassKeyTyped
        if(txt_confpass.getText().length()<16){
            txt_confpass.setEditable(true);
        }
        else {
            batastxt = txt_confpass.getText().substring(0, 15);
            txt_confpass.setText(batastxt);
        }
    }//GEN-LAST:event_txt_confpassKeyTyped

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        username = txt_username.getText();
        password = txt_password.getText();
        confpass = txt_confpass.getText();
        
        if (password.equals(confpass) && username.length() != 0 && password.length() != 0){
            try{
                Statement stasql = (Statement)kon.Connect().createStatement();
                kueri=("insert into user (username,password) values ('"+username+"','"+password+"');");
                stasql.executeUpdate(kueri);
                stasql.close();
                JOptionPane.showMessageDialog(null,"Pendaftaran Berhasil");
                
                //Statement setelah berhasil register
            } catch(Exception t){
                JOptionPane.showMessageDialog(null,"Pendaftaran Akun Gagal\nNama Pengguna Sudah Digunakan");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Pendaftaran Akun Gagal\nTerdapat Kesalahan Pada Pengisian Data");
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_confpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_confpassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            btn_registerActionPerformed(null);
        }
    }//GEN-LAST:event_txt_confpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_confpass;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_txt_confpass;
    private javax.swing.JLabel lbl_txt_password;
    private javax.swing.JLabel lbl_txt_username;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_confpass;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
